#!/usr/bin/env python3

import argparse
import subprocess
import shutil
import sys
from pathlib import Path


def _clean_docs_directory(docs_dir: Path, preserve_index: bool) -> int:
    """Remove old generated files from docs/ to prevent stale GitHub Pages assets.

    Args:
        docs_dir: Directory served by GitHub Pages.
        preserve_index: Whether to keep docs/index.html untouched.

    Returns:
        Number of entries removed.
    """
    if not docs_dir.exists():
        return 0

    preserved_items = {".nojekyll", "CNAME"}
    if preserve_index:
        preserved_items.add("index.html")

    removed_entries = 0
    for item in docs_dir.iterdir():
        if item.name in preserved_items:
            continue

        try:
            if item.is_dir():
                shutil.rmtree(item)
            else:
                item.unlink()
            removed_entries += 1
        except OSError as exc:
            print(f"  [WARN] Failed to remove stale docs item {item.name}: {exc}")

    return removed_entries


def _copy_build_to_docs(build_web_dir: Path, docs_dir: Path, preserve_index: bool) -> tuple[int, int]:
    """Copy pygbag output from build/web to docs/.

    Args:
        build_web_dir: Source directory generated by pygbag.
        docs_dir: Destination directory served by GitHub Pages.
        preserve_index: Whether to skip replacing docs/index.html.

    Returns:
        Tuple of (copied_count, skipped_count).
    """
    copied_count = 0
    skipped_count = 0

    for item in build_web_dir.iterdir():
        dest_path = docs_dir / item.name

        if preserve_index and item.name == "index.html":
            print("  [SKIP] index.html (preserving docs/index.html)")
            skipped_count += 1
            continue

        try:
            if item.is_dir():
                if dest_path.exists():
                    shutil.rmtree(dest_path)
                shutil.copytree(item, dest_path)
                print(f"  [DIR] Copied folder: {item.name}/")
            else:
                shutil.copy2(item, dest_path)
                print(f"  [FILE] Copied: {item.name}")
            copied_count += 1
        except OSError as exc:
            print(f"  [WARN] Failed to copy {item.name}: {exc}")

    return copied_count, skipped_count


def build_web(*, preserve_index: bool, clean_docs: bool) -> None:
    """Build the web package with pygbag and sync output into docs/.

    Args:
        preserve_index: Keep docs/index.html instead of replacing it.
        clean_docs: Remove stale generated assets in docs/ before copy.

    Raises:
        FileNotFoundError: If build output is missing.
        subprocess.CalledProcessError: If pygbag build fails.
    """
    project_root = Path(__file__).parent
    build_web_dir = project_root / "build" / "web"
    docs_dir = project_root / "docs"

    print("[BUILD] Building pygame project for web with pygbag...")

    try:
        subprocess.run(
            [sys.executable, "-m", "pygbag", "--build", str(project_root)],
            check=True,
            cwd=project_root
        )
    except subprocess.CalledProcessError as e:
        print(f"[ERROR] pygbag build failed with exit code {e.returncode}")
        raise
    except FileNotFoundError:
        print("[ERROR] pygbag not found. Install it with: pip install pygbag")
        raise
    
    if not build_web_dir.exists() or not build_web_dir.is_dir():
        raise FileNotFoundError(f"Build output not found at {build_web_dir}")

    print("[SYNC] Syncing build output to docs/...")

    docs_dir.mkdir(exist_ok=True)

    removed_entries = 0
    if clean_docs:
        print("[CLEAN] Removing stale docs assets before copy...")
        removed_entries = _clean_docs_directory(docs_dir, preserve_index)
        print(f"  [OK] Removed stale entries: {removed_entries}")

    files_copied, files_skipped = _copy_build_to_docs(build_web_dir, docs_dir, preserve_index)

    print("[DONE] Build complete!")
    print(f"   Stale entries removed: {removed_entries}")
    print(f"   Files/folders copied: {files_copied}")
    print(f"   Files skipped: {files_skipped}")
    print(f"   Output directory: {docs_dir}")
    print("\nNext steps:")
    print("   1. Test locally if needed")
    print("   2. git add docs/")
    print("   3. git commit -m 'Update web build'")
    print("   4. git push")


def parse_args() -> argparse.Namespace:
    """Parse CLI options for web build synchronization."""
    parser = argparse.ArgumentParser(
        description="Build with pygbag and sync output to docs/ for GitHub Pages."
    )
    parser.set_defaults(preserve_index=True, clean_docs=True)
    parser.add_argument(
        "--replace-index",
        dest="preserve_index",
        action="store_false",
        help="Replace docs/index.html with build/web/index.html.",
    )
    parser.add_argument(
        "--clean-docs",
        dest="clean_docs",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Clean stale generated files in docs/ before copying (default: enabled).",
    )
    return parser.parse_args()


if __name__ == "__main__":
    try:
        args = parse_args()
        build_web(preserve_index=args.preserve_index, clean_docs=args.clean_docs)
    except Exception as e:
        print(f"\n[FAILED] Build failed: {e}")
        sys.exit(1)
